workflows:
  expo-ios-workflow:
    name: Build Expo iOS App
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: Encrypted_Expo_Token_Here
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Expo iOS app
        script: |
          npx expo install
          npx expo export --platform ios --output-dir dist
    artifacts:
      - dist/ios/**/*.ipa
    publishing:
      email:
        recipients:
          - chaoaau@gmail.com
